server:
  port: 8889
spring:
  application:
    name: Microservices.Demo.ConfigServer
  cloud:    
    config:
      server:
        git:
          uri: https://github.com/christianCarranza/proyecto-microservicios-net-2023.git
          search-paths:
            - '/app/Infrastructure/Microservices.Config.Repository/{application}'
          defaultLabel: master
eureka:
  instance:
    appName: Microservices.Demo.ConfigServer
    hostname: microservices.demo.configserver
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://microservices.demo.discoveryserver:8761/eureka/